"use client";

import { Boxes } from "lucide-react";
import { StageBadge } from "@/components/ui/stage-badge";
import { EmptyState } from "@/components/feedback/empty-state";
import { useRecentGeneratedProjectsSuspense } from "@/features/dashboard/api/use-dashboard-data";
import { formatRelativeTime } from "@/lib/utils/formatters";
import { generatedProjectStatusToStage } from "@/lib/utils/status-mapping";

export function LatestGeneratedProjects() {
  const { data: generatedProjects } = useRecentGeneratedProjectsSuspense(6);

  if (generatedProjects.length === 0) {
    return (
      <EmptyState
        icon={Boxes}
        title="No generated projects yet"
        description="Projects generated by the orchestrator's Code Generator agent appear here."
      />
    );
  }

  return (
    <ul className="space-y-1">
      {generatedProjects.map((project) => (
        <li
          key={project.id}
          className="flex items-center justify-between gap-3 rounded-md px-2 py-2"
        >
          <div className="min-w-0">
            <p className="truncate text-sm font-medium">
              {project.framework} · v{project.version}
              {project.model_name && <span className="text-muted-foreground"> · {project.model_name}</span>}
            </p>
            <p className="text-xs text-muted-foreground">
              {project.quality_score !== null ? `Quality ${(project.quality_score * 100).toFixed(0)}% · ` : ""}
              {formatRelativeTime(project.created_at)}
            </p>
          </div>
          <StageBadge status={generatedProjectStatusToStage(project.status)} label={project.status} />
        </li>
      ))}
    </ul>
  );
}
