"use client";

import { useParams } from "next/navigation";
import { FileText, FlaskConical, Share2, Sparkles } from "lucide-react";
import { CardSkeleton } from "@/components/feedback/skeletons";
import { EmptyState } from "@/components/feedback/empty-state";
import { StageBadge } from "@/components/ui/stage-badge";
import { StatCard } from "@/components/ui/stat-card";
import { SectionCard } from "@/components/ui/section-card";
import { QuickActions } from "@/features/workspace/components/quick-actions";
import { usePipelineTracker } from "@/features/workspace/api/use-pipeline-tracker";
import { formatBytes, formatDate, formatDuration } from "@/lib/utils/formatters";
import {
  executionRunStatusToStage,
  generatedProjectStatusToStage,
  knowledgeExtractionStatusToStage,
  paperStatusToStage,
} from "@/lib/utils/status-mapping";

export default function ProjectOverviewPage() {
  const params = useParams<{ projectId: string }>();
  const { stages, isLoading, paper, knowledge, graph, generatedProject, executionRun } = usePipelineTracker(
    params.projectId,
  );

  if (isLoading) {
    return (
      <div className="grid gap-4 sm:grid-cols-2">
        <CardSkeleton />
        <CardSkeleton />
        <CardSkeleton />
        <CardSkeleton />
      </div>
    );
  }

  const currentStage = stages.find((s) => s.status === "running") ?? [...stages].reverse().find((s) => s.status !== "pending");

  return (
    <div className="space-y-6">
      <QuickActions projectId={params.projectId} paper={paper} knowledge={knowledge} generatedProject={generatedProject} />

      <StatCard
        label="Current pipeline status"
        value={currentStage?.label ?? "Not started"}
        icon={Sparkles}
      />

      <div className="grid gap-4 sm:grid-cols-2">
        <SectionCard title="Paper" description="Uploaded source paper">
          {!paper ? (
            <EmptyState icon={FileText} title="No paper uploaded" description="Use Quick Actions above to upload one." />
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="truncate text-sm font-medium">{paper.original_filename}</p>
                <StageBadge status={paperStatusToStage(paper.status)} label={paper.status} />
              </div>
              <p className="text-xs text-muted-foreground">
                {formatBytes(paper.size_bytes)} · Uploaded {formatDate(paper.created_at)}
              </p>
            </div>
          )}
        </SectionCard>

        <SectionCard title="Knowledge extraction" description="Structured knowledge extracted from the paper">
          {!knowledge ? (
            <EmptyState icon={Sparkles} title="Not started" description="Extract knowledge once the paper has finished parsing." />
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium">Version {knowledge.version}</p>
                <StageBadge status={knowledgeExtractionStatusToStage(knowledge.status)} label={knowledge.status} />
              </div>
              <p className="text-xs text-muted-foreground">
                {knowledge.model_name ?? "Unknown model"} · {formatDate(knowledge.created_at)}
              </p>
            </div>
          )}
        </SectionCard>

        <SectionCard title="Knowledge graph" description="Built from the latest completed extraction">
          {!graph ? (
            <EmptyState icon={Share2} title="Not built yet" description="The graph builds automatically once knowledge extraction completes." />
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium">Graph ready</p>
                <StageBadge status="success" label="built" />
              </div>
              <p className="text-xs text-muted-foreground">
                {graph.nodes.length} nodes · {graph.relationships.length} relationships
              </p>
            </div>
          )}
        </SectionCard>

        <SectionCard title="Generated project" description="Code generated by the orchestrator">
          {!generatedProject ? (
            <EmptyState icon={Sparkles} title="Not generated yet" description="Generation is triggered by the AI Assistant's orchestrator." />
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium">
                  {generatedProject.framework} · v{generatedProject.version}
                </p>
                <StageBadge status={generatedProjectStatusToStage(generatedProject.status)} label={generatedProject.status} />
              </div>
              <p className="text-xs text-muted-foreground">
                {generatedProject.quality_score !== null
                  ? `Quality ${Math.round(generatedProject.quality_score * 100)}%`
                  : "Quality not scored yet"}{" "}
                · {formatDate(generatedProject.created_at)}
              </p>
            </div>
          )}
        </SectionCard>

        <SectionCard title="Latest execution run" description="Most recent training run" className="sm:col-span-2">
          {!executionRun ? (
            <EmptyState icon={FlaskConical} title="No runs yet" description="Trigger a run once a generated project is ready." />
          ) : (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <p className="text-sm font-medium">
                  {executionRun.device.toUpperCase()} · v{executionRun.version}
                </p>
                <StageBadge status={executionRunStatusToStage(executionRun.status)} label={executionRun.status} />
              </div>
              <p className="text-xs text-muted-foreground">
                {executionRun.started_at && executionRun.finished_at
                  ? `Took ${formatDuration(
                      Math.round((new Date(executionRun.finished_at).getTime() - new Date(executionRun.started_at).getTime()) / 1000),
                    )}`
                  : executionRun.started_at
                    ? `Started ${formatDate(executionRun.started_at)}`
                    : "Queued"}
                {executionRun.exit_code !== null ? ` · exit ${executionRun.exit_code}` : ""}
              </p>
            </div>
          )}
        </SectionCard>
      </div>
    </div>
  );
}
